[[plugins]]
repo = "joshdick/onedark.vim"
hook_add = '''
colorscheme onedark

'''

[[plugins]]
repo = "vim-airline/vim-airline"

[[plugins]]
repo = "Shougo/denite.nvim"
hook_add = '''
if executable("ag")
  call denite#custom#var('file_rec', 'command', ['ag', '--follow', '--nocolor', '--nogroup', '-g', ''])
  call denite#custom#var("grep", "command", ["ag"])
  nnoremap <silent> ,g :<C-u>Denite -buffer-name=search -mode=normal grep<CR>
endif
'''
[[plugins]]
repo = "cespare/vim-toml"

[[plugins]]
repo = "elixir-editors/vim-elixir"

[[plugins]]
repo = "kbrw/elixir.nvim"

[[plugins]]
repo = "cocopon/vaffle.vim"

[[plugins]]
repo = "Shougo/deoplete.nvim"
hook_add = '''
let g:deoplete#enable_at_startup = 1
'''
[[plugins]]
repo = "osyo-manga/vim-monster"
hook_add = '''
let g:deoplete#sources#omni#input_patterns = { "ruby": "[^. *\t]\.\w*\|\h\w*::"}
'''
