[[plugins]]
repo = "KeitaNakamura/neodark.vim"
hook_add = """
let g:neodark#background = '#202020'
let g:neodark#use_256color = 1
let g:neodark#terminal_transparent = 1
let g:lightline = {}
let g:lightline.colorscheme = 'neodark'
"""

[[plugins]]
repo = "vim-airline/vim-airline"

[[plugins]]
repo = "Shougo/neomru.vim"

[[plugins]]
repo = "Shougo/denite.nvim"
dependent = ["neomru.vim"]
hook_add = """
nmap <silent> <C-x><C-[> :<C-u>Denite file<CR>
nmap <silent> <C-x><C-f> :<C-u>Denite file_rec<CR>
nmap <silent> <C-x><C-g> :<C-u>Denite grep<CR>
nmap <silent> <C-x><C-m> :<C-u>Denite file_mru<CR>
nmap <silent> <C-x><C-y> :<C-u>Denite neoyank<CR>
call denite#custom#var('file_rec', 'command', ["rg", "-u", "--files", "-g", "!.git", "-g", "!_build", "-g", "!node_modules"])
call denite#custom#var("grep", "command", ["rg"])
call denite#custom#source('file_rec', 'matchers', ['matcher_fuzzy','matcher_ignore_globs'])
call denite#custom#filter("matcher_ignore_globs", "ignore_globs", [".git/", "_build/", "images/", "imgs/", "*.o", "*.make", "*.beam"])
nnoremap <silent> ,g :<C-u>Denite -buffer-name=search -mode=normal grep<CR>
"""

[[plugins]]
repo = "Shougo/vimproc.vim"
build = "make"

[[plugins]]
repo = "cocopon/vaffle.vim"

# [[plugins]]
# repo = "osyo-manga/vim-monster"
# hook_add = """
# let g:deoplete#omni_patterns = {}
# let g:deoplete#omni_patterns.ruby = ['[^. *\t]\.\w*', '\h\w*::']
# """
# on_ft = ["rb", "ruby"]

[[plugins]]
repo = "kana/vim-textobj-user"

[[plugins]]
repo = "kana/vim-operator-user"

[[plugins]]
repo = "rhysd/vim-textobj-ruby"

[[plugins]]
repo = "tyru/caw.vim"
hook_add = """
nmap <C-_> <Plug>(caw:hatpos:toggle)
vmap <C-_> <Plug>(caw:hatpos:toggle)
"""

[[plugins]]
repo = "airblade/vim-gitgutter"
